const colors =
  "[--paper:oklch(98%_.006_240)] [--ink:oklch(23%_.03_255)] [--muted:oklch(45%_.028_252)] [--line:oklch(84%_.016_242)] [--indigo:oklch(45%_.16_250)] [--green:oklch(45%_.09_175)] [--saffron:oklch(72%_.14_78)] [--red:oklch(47%_.18_25)]";

const styles: Record<string, string> = {
  workspace: `mx-auto max-w-[1180px] bg-[var(--paper)] p-4 text-[var(--ink)] font-sans antialiased ${colors} [&_*]:box-border [&_button]:font-inherit [&_select]:font-inherit [&_textarea]:font-inherit [&_input]:font-inherit [&_button:focus-visible]:outline-3 [&_button:focus-visible]:outline-[var(--saffron)] [&_select:focus-visible]:outline-3 [&_select:focus-visible]:outline-[var(--saffron)] [&_textarea:focus-visible]:outline-3 [&_textarea:focus-visible]:outline-[var(--saffron)] [&_input:focus-visible]:outline-3 [&_input:focus-visible]:outline-[var(--saffron)] sm:p-8 lg:p-12`,
  roleSwitchBar: `mx-auto flex max-w-[1180px] items-center justify-between gap-4 border-b border-[var(--line)] px-5 py-[.7rem] text-[.82rem] text-[var(--muted)] [&_button]:min-h-10 [&_button]:cursor-pointer [&_button]:border [&_button]:border-[var(--indigo)] [&_button]:bg-transparent [&_button]:px-3 [&_button]:py-[.45rem] [&_button]:font-bold [&_button]:text-[var(--indigo)]`,
  viewSwitchBar: "mx-auto flex max-w-[1180px] items-center justify-between gap-4 border-b border-[var(--line)] px-5 py-[.7rem] text-[.82rem] text-[var(--muted)] [&_button]:min-h-10 [&_button]:cursor-pointer [&_button]:border [&_button]:border-[var(--indigo)] [&_button]:bg-transparent [&_button]:px-3 [&_button]:py-[.45rem] [&_button]:font-bold [&_button]:text-[var(--indigo)]",
  skipLink: "fixed left-4 -top-20 z-[5] bg-[var(--indigo)] px-4 py-3 text-[var(--paper)] focus:top-4",
  masthead: "flex items-start justify-between gap-4 border-b-[3px] border-[var(--ink)] pb-6 pt-[clamp(1rem,4vw,3rem)]",
  eyebrow: "mb-[.35rem] mt-0 text-[.78rem] font-semibold uppercase tracking-[.1em] text-[var(--indigo)]",
  kicker: "mb-[.35rem] mt-0 text-[.78rem] font-semibold uppercase tracking-[.1em] text-[var(--indigo)]",
  roleLine: "mt-3 text-base text-[var(--muted)] [&_b]:font-bold [&_b]:text-[var(--ink)]",
  wardStamp: "flex shrink-0 items-center gap-2 bg-[var(--indigo)] p-[.7rem] text-[var(--paper)] [&_b]:font-serif [&_b]:text-[2.5rem] [&_b]:leading-[.8] [&_span]:text-[.75rem] [&_span]:font-bold [&_span]:uppercase [&_span]:leading-[1.1]",
  demoNotice: "my-4 mb-9 max-w-[75ch] border-l-[3px] border-[var(--saffron)] py-3 pl-4 text-[.94rem] leading-[1.45] text-[oklch(33%_.03_70)] [&_strong]:text-[var(--ink)]",
  ledgerSummary: "mb-12 grid grid-cols-2 border-l border-t border-[var(--line)] min-[721px]:grid-cols-4 [&>div]:flex [&>div]:min-h-32 [&>div]:flex-col [&>div]:justify-end [&>div]:border-b [&>div]:border-r [&>div]:border-[var(--line)] [&>div]:p-4 [&_span]:text-[.8rem] [&_span]:text-[var(--muted)] [&_small]:text-[.8rem] [&_small]:text-[var(--muted)] [&_strong]:my-1 [&_strong]:font-serif [&_strong]:text-[clamp(1.55rem,3vw,2.35rem)] [&_strong]:leading-none [&_strong]:tracking-[-.04em] [&_strong]:tabular-nums",
  section: "mb-12 max-[720px]:mb-9",
  sectionHeading: "mb-0 flex items-end justify-between gap-4 border-b border-[var(--line)] pb-4 max-[720px]:items-start max-[720px]:flex-col [&_h2]:m-0 [&_h2]:font-serif [&_h2]:text-[clamp(1.55rem,3vw,2.3rem)] [&_h2]:leading-[1.05] [&_h2]:tracking-[-.03em] [&>p]:m-0 [&>p]:max-w-[34ch] [&>p]:text-[.9rem] [&>p]:leading-[1.4] [&>p]:text-[var(--muted)]",
  issueLayout: "grid items-start border-b border-[var(--line)] min-[721px]:grid-cols-[minmax(0,.85fr)_minmax(0,1.15fr)]",
  issueList: "border-r border-[var(--line)] max-[720px]:border-r-0",
  issueRow: "grid min-h-[76px] w-full cursor-pointer grid-cols-[2rem_1fr] items-center gap-3 border-0 border-b border-[var(--line)] bg-transparent p-3 text-left text-inherit hover:bg-[oklch(93.5%_.035_244)] min-[721px]:grid-cols-[2.25rem_1fr_auto]",
  activeIssue: "!bg-[oklch(93.5%_.035_244)]",
  issueNumber: "text-[.75rem] font-semibold tabular-nums tracking-[.06em] text-[var(--muted)]",
  recordNumber: "text-[.75rem] font-semibold tabular-nums tracking-[.06em] text-[var(--muted)]",
  issueWords: "grid min-w-0 gap-[.3rem] [&_b]:text-[.95rem] [&_b]:leading-[1.25] [&_small]:text-[.75rem] [&_small]:text-[var(--muted)]",
  statusPill: "whitespace-nowrap rounded-full px-2 py-[.35rem] text-[.7rem] font-semibold leading-[1.1] max-[720px]:col-start-2 max-[720px]:justify-self-start",
  requested: "text-[oklch(32%_.07_69)] bg-[oklch(88%_.07_80)]",
  inProgress: "text-[oklch(32%_.11_250)] bg-[oklch(91%_.04_244)]",
  completed: "text-[oklch(28%_.07_175)] bg-[oklch(90%_.05_175)]",
  issueDetail: "p-5 max-[720px]:px-0",
  detailTop: "flex items-center justify-between gap-3",
  issueDescription: "m-0 max-w-[62ch] leading-[1.55]",
  detailMeta: "my-6 grid grid-cols-2 gap-3 border-b border-t border-[var(--line)] py-4 min-[721px]:grid-cols-3 [&_div]:min-w-0 [&_dt]:text-[.72rem] [&_dt]:font-bold [&_dt]:uppercase [&_dt]:text-[var(--muted)] [&_dd]:mt-1 [&_dd]:overflow-wrap-anywhere [&_dd]:text-[.87rem] [&_dd]:font-bold",
  evidence: "my-6",
  evidenceStrip: "flex gap-3 overflow-x-auto pb-1",
  statusField: "my-6 mt-6 border border-[var(--line)] p-4 [&_legend]:px-1 [&_legend]:font-semibold [&_p]:my-1 [&_p]:mb-4 [&_p]:max-w-[60ch] [&_p]:text-[.87rem] [&_p]:leading-[1.4] [&_p]:text-[var(--muted)]",
  statusActions: "flex flex-wrap gap-2 [&_button]:min-h-11 [&_button]:cursor-pointer [&_button]:border [&_button]:border-current [&_button]:bg-transparent [&_button]:px-3 [&_button]:py-[.6rem] [&_button]:font-semibold [&_button]:text-[var(--indigo)] [&_button]:active:translate-y-px",
  currentStatus: "!bg-[var(--indigo)] !text-[var(--paper)]",
  escalationBand: "mt-4 flex gap-3 border-b border-[var(--line)] border-t-2 border-[var(--red)] py-3 text-[.85rem] leading-[1.4] [&_b]:whitespace-nowrap [&_b]:text-[var(--red)]",
  auditFeedback: "flex gap-4 bg-[oklch(92%_.04_175)] px-4 py-[.9rem] text-[.86rem] text-[oklch(29%_.055_175)] [&>b]:shrink-0 max-[720px]:flex-col",
  auditLine: "m-0 flex gap-[.55rem] leading-[1.45] [&_span]:font-bold [&_span]:text-[var(--green)]",
  secondaryColumns: "grid min-[721px]:grid-cols-2 min-[721px]:gap-[clamp(1.5rem,4vw,4rem)] max-[720px]:gap-0 max-[720px]:[&>.section+.section]:border-t-2 max-[720px]:[&>.section+.section]:border-[var(--ink)] max-[720px]:[&>.section+.section]:pt-9",
  taskList: "m-0 list-none p-0 [&_li]:flex [&_li]:items-center [&_li]:justify-between [&_li]:gap-4 [&_li]:border-b [&_li]:border-[var(--line)] [&_li]:py-[.9rem] [&_label]:flex [&_label]:min-w-0 [&_label]:cursor-pointer [&_label]:items-center [&_label]:gap-3 [&_label_span]:grid [&_label_span]:gap-1 [&_small]:text-[.8rem] [&_small]:leading-[1.35] [&_small]:text-[var(--muted)]",
  doneMark: "shrink-0 bg-[oklch(90%_.05_175)] px-[.45rem] py-1 text-[.7rem] font-semibold text-[oklch(28%_.07_175)]",
  openMark: "shrink-0 bg-[oklch(88%_.07_80)] px-[.45rem] py-1 text-[.7rem] font-semibold text-[oklch(32%_.07_69)]",
  noticeForm: "grid gap-2 py-4 [&_label]:text-[.88rem] [&_label]:font-semibold [&_label_span]:font-normal [&_label_span]:text-[var(--muted)] [&_textarea]:min-h-28 [&_textarea]:w-full [&_textarea]:resize-y [&_textarea]:border [&_textarea]:border-[var(--line)] [&_textarea]:bg-[oklch(99%_.004_240)] [&_textarea]:p-3 [&_textarea]:leading-[1.45] [&_textarea]:text-[var(--ink)] [&_textarea]:placeholder:text-[var(--muted)] [&>div]:flex [&>div]:items-center [&>div]:justify-between [&>div]:gap-4 [&_small]:text-[var(--muted)] [&_button]:min-h-11 [&_button]:cursor-pointer [&_button]:border [&_button]:border-[var(--indigo)] [&_button]:bg-[var(--indigo)] [&_button]:px-3 [&_button]:py-[.6rem] [&_button]:font-semibold [&_button]:text-[var(--paper)] [&_button]:disabled:cursor-not-allowed [&_button]:disabled:opacity-50",
  noticeList: "m-0 list-none border-t border-[var(--line)] p-0 [&_li]:border-b [&_li]:border-[var(--line)] [&_li]:py-[.85rem] [&_p]:mb-[.35rem] [&_p]:mt-0 [&_p]:text-[.9rem] [&_p]:leading-[1.4] [&_small]:text-[.75rem] [&_small]:text-[var(--muted)]",
  compliance: "border-t-[3px] border-[var(--ink)] bg-[oklch(96%_.018_244)] p-5 max-[720px]:-mx-4 [&>div]:mt-4 [&>div]:grid [&>div]:gap-[.65rem] [&>div]:text-[.88rem]",
  tableWrap: "overflow-x-auto",
  wardTable: "w-full min-w-[700px] border-collapse text-[.86rem] tabular-nums max-[720px]:min-w-0 max-[720px]:[&_thead]:hidden max-[720px]:[&_tbody]:block max-[720px]:[&_tr]:block max-[720px]:[&_tr]:border-b-2 max-[720px]:[&_tr]:border-[var(--ink)] max-[720px]:[&_tr]:py-3 max-[720px]:[&_td]:grid max-[720px]:[&_td]:grid-cols-[8rem_1fr] max-[720px]:[&_td]:gap-2 max-[720px]:[&_td]:border-0 max-[720px]:[&_td]:py-[.45rem] [&_th]:border-b-2 [&_th]:border-[var(--ink)] [&_th]:p-3 [&_th]:text-left [&_th]:text-[.72rem] [&_th]:uppercase [&_th]:tracking-[.06em] [&_th]:text-[var(--muted)] [&_td]:border-b [&_td]:border-[var(--line)] [&_td]:p-3 [&_td]:align-top [&_td_b]:block [&_td_b]:text-[.88rem] [&_td_span]:mt-1 [&_td_span]:block [&_td_span]:text-[.76rem] [&_td_span]:leading-[1.3] [&_td_span]:text-[var(--muted)] [&_td:first-child_b]:font-serif [&_td:first-child_b]:text-[1.4rem] max-[720px]:[&_td:first-child_b]:text-[1.2rem]",
  escalationList: "[&_article]:grid [&_article]:grid-cols-1 [&_article]:gap-4 [&_article]:border-b [&_article]:border-[var(--line)] [&_article]:py-4 min-[721px]:[&_article]:grid-cols-[minmax(0,1fr)_10rem] [&_h3]:mb-1 [&_h3]:mt-2 [&_h3]:font-serif [&_h3]:text-[1.15rem] [&_h3]:leading-[1.12] [&_p]:m-0 [&_p]:text-[.86rem] [&_p]:leading-[1.4] [&_p]:text-[var(--muted)] [&_label]:grid [&_label]:content-start [&_label]:gap-[.4rem] [&_label]:text-[.75rem] [&_label]:font-semibold [&_select]:min-h-11 [&_select]:w-full [&_select]:border [&_select]:border-[var(--indigo)] [&_select]:bg-[oklch(99%_.004_240)] [&_select]:p-2 [&_select]:text-[var(--indigo)]",
  budgetTotal: "grid gap-[.2rem] border-b-2 border-[var(--ink)] py-4 [&_span]:text-[.8rem] [&_span]:text-[var(--muted)] [&_small]:text-[.8rem] [&_small]:text-[var(--muted)] [&_strong]:font-serif [&_strong]:text-[2rem] [&_strong]:tracking-[-.04em] [&_strong]:tabular-nums",
  expenditureList: "m-0 list-none p-0 [&_li]:flex [&_li]:justify-between [&_li]:gap-4 [&_li]:border-b [&_li]:border-[var(--line)] [&_li]:py-[.85rem] [&_li>div]:grid [&_li>div]:gap-1 [&_b]:text-[.88rem] [&_b]:leading-[1.3] [&_small]:text-[.75rem] [&_small]:text-[var(--muted)] [&_li>strong]:whitespace-nowrap [&_li>strong]:text-[.85rem] [&_li>strong]:tabular-nums",
  alertList: "m-0 list-none p-0 [&_li]:flex [&_li]:gap-3 [&_li]:border-b [&_li]:border-[var(--line)] [&_li]:py-[.9rem] [&_li>div]:grid [&_li>div]:gap-[.3rem] [&_b]:text-[.92rem] [&_p]:m-0 [&_p]:text-[.86rem] [&_p]:leading-[1.4] [&_p]:text-[var(--muted)] [&_small]:text-[.75rem] [&_small]:text-[var(--muted)]",
};

export default styles;
