import Link from "next/link";
import { ArrowUpRight, MapPin } from "lucide-react";

import type { PublicDemoData } from "@/data/demo";
import type { DemoSession, Official, Ward } from "@/lib/domain/types";
import { formatWardLabel, formatWardNumber } from "@/lib/domain/ward-label";

type MunicipalityPageProps = { data: PublicDemoData; session: DemoSession };

const formatRupees = (amount: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(amount);
const formatDate = (value: string) => new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value));
const currentParshadForWard = (officials: Official[], wardId: string) => officials.find((official) => official.current && official.wardId === wardId && official.roleLabel.toLowerCase().includes("parshad"));

function FinanceRow({ ward, amount }: { ward: Ward; amount: number }) {
  return <li className="municipality-finance-row"><span><strong>{formatWardLabel(ward.number)}</strong></span><span><strong>{formatRupees(amount)}</strong></span></li>;
}

export function MunicipalityPage({ data, session }: MunicipalityPageProps) {
  const totalAllocated = data.wards.reduce((sum, ward) => sum + ward.allocatedBudget, 0);
  const totalSpent = data.wards.reduce((sum, ward) => sum + ward.spentBudget, 0);
  const demoFinance = data.wards.some((ward) => ward.budgetIsDemo) || data.expenditures.some((item) => item.isDemo);
  const recentExpenditures = [...data.expenditures].sort((left, right) => new Date(right.spentAt).getTime() - new Date(left.spentAt).getTime()).slice(0, 5);

  return <main className="municipality-page" id="main-content">
    <header className="municipality-hero"><div><p className="municipality-kicker">Municipality record / नगर रिकॉर्ड</p><h1>{data.municipality.name}</h1><p className="municipality-location"><MapPin size={16} aria-hidden="true" /> {data.municipality.district}, {data.municipality.state}</p><p className="municipality-lede">A read-only public account of the wards, representatives, and civic funds recorded for this municipality.</p></div><div className="municipality-stamp" aria-label={`${data.wards.length} wards in register`}><strong>{data.wards.length}</strong><span>wards<br />in register</span></div></header>
    <div className="municipality-notice" role="note"><strong>Public record</strong><span>Only municipality, ward, representative, and public finance fields are shown here. Private resident details are not part of this page.</span></div>
    <section className="municipality-section" aria-labelledby="municipality-details-title"><div className="municipality-section-heading"><div><p className="municipality-kicker">At a glance</p><h2 id="municipality-details-title">Municipality details</h2></div><p>Every figure below comes from the shared municipality record.</p></div><dl className="municipality-facts"><div><dt>Name</dt><dd>{data.municipality.name}</dd></div><div><dt>District</dt><dd>{data.municipality.district}</dd></div><div><dt>State</dt><dd>{data.municipality.state}</dd></div><div><dt>Ward count</dt><dd>{data.wards.length}</dd></div></dl></section>
    <section className="municipality-section" aria-labelledby="ward-register-title"><div className="municipality-section-heading"><div><p className="municipality-kicker">Ward register</p><h2 id="ward-register-title">Ward representatives</h2></div><p>Names and terms are shown only when they exist in the public record.</p></div><div className="municipality-ward-table-wrap"><table className="municipality-ward-table"><thead><tr><th scope="col">Ward</th><th scope="col">Ward Parshad</th><th scope="col">Term</th><th scope="col">Actions</th></tr></thead><tbody>{data.wards.map((ward) => { const representative = currentParshadForWard(data.officials, ward.id); return <tr key={ward.id}><th scope="row" data-label="Ward">{formatWardNumber(ward.number)}</th><td data-label="Ward Parshad">{representative?.name ?? <span className="municipality-missing">Not listed</span>}</td><td data-label="Term">{representative?.termNumber ? `${representative.termNumber}${representative.termNumber === 1 ? "st" : representative.termNumber === 2 ? "nd" : representative.termNumber === 3 ? "rd" : "th"} term` : <span className="municipality-missing">Term not recorded</span>}</td><td data-label="Actions"><Link className="municipality-table-action" href={`/wards?ward=${ward.id}`}>Open ward <ArrowUpRight size={15} aria-hidden="true" /></Link></td></tr>; })}</tbody></table></div></section>
    <section className="municipality-section municipality-finance" aria-labelledby="finance-title"><div className="municipality-section-heading"><div><p className="municipality-kicker">Public work account</p><h2 id="finance-title">Ward funds & commitments</h2></div><p>Allocation and recorded spending are kept visible together for public review.</p></div><div className="municipality-ledger-summary" aria-label="Municipality finance summary"><div><span>Total allocated</span><strong>{formatRupees(totalAllocated)}</strong><small>{demoFinance ? "Temporary demo value" : "Recorded allocation"}</small></div><div><span>Recorded spending</span><strong>{formatRupees(totalSpent)}</strong><small>{data.expenditures.length} commitment records</small></div></div><div className="municipality-finance-grid"><div><h3>Ward allocations</h3><ul className="municipality-finance-list">{data.wards.map((ward) => <FinanceRow key={ward.id} ward={ward} amount={ward.allocatedBudget} />)}</ul></div><div><h3>Recent commitments</h3>{recentExpenditures.length ? <ul className="municipality-finance-list">{recentExpenditures.map((expense) => { const ward = data.wards.find((candidate) => candidate.id === expense.wardId); return <li className="municipality-finance-row" key={expense.id}><span><strong>{ward ? formatWardLabel(ward.number) : "Ward record"}</strong><small>{expense.description} · {formatDate(expense.spentAt)}</small></span><span><strong>{formatRupees(expense.amount)}</strong></span></li>; })}</ul> : <p className="municipality-empty">No public commitment is recorded yet.</p>}</div></div>{demoFinance ? <p className="municipality-footnote">Some finance values are temporary demo records and are labelled until authoritative figures replace them.</p> : null}</section>
    <nav className="municipality-footer-nav" aria-label="Municipality navigation"><Link href="/overview">Return to your ward <ArrowUpRight size={16} aria-hidden="true" /></Link><span>Viewing as {session.role === "corporation_admin" ? "corporation official" : session.role === "parshad" ? "ward Parshad" : "citizen"}</span></nav>
  </main>;
}
