const colors =
  "[--paper:oklch(98%_.006_240)] [--ink:oklch(23%_.03_255)] [--muted:oklch(45%_.028_252)] [--rule:oklch(84%_.016_242)] [--indigo:oklch(45%_.16_250)] [--indigo-soft:oklch(93.5%_.035_244)] [--green:oklch(45%_.09_175)] [--green-soft:oklch(92%_.04_175)] [--marigold:oklch(72%_.14_78)] [--red:oklch(47%_.18_25)]";

const styles: Record<string, string> = {
  experience: `relative flex min-h-full flex-1 flex-col bg-[var(--paper)] text-[var(--ink)] font-sans antialiased ${colors} [&_*]:box-border [&_button]:font-inherit [&_input]:font-inherit [&_textarea]:font-inherit [&_button:focus-visible]:outline-3 [&_button:focus-visible]:outline-[var(--marigold)] [&_a:focus-visible]:outline-3 [&_a:focus-visible]:outline-[var(--marigold)]`,
  skipLink: "absolute left-4 -top-20 z-10 bg-[var(--ink)] px-4 py-3 text-[var(--paper)] focus:top-4",
  masthead: "mx-auto flex min-h-[4.5rem] w-full max-w-[var(--content-max,76rem)] items-center justify-between border-b border-[var(--rule)] px-[clamp(1.25rem,4vw,2rem)]",
  wordmark: "min-h-11 cursor-pointer border-0 bg-transparent px-0 py-2.5 text-[1.3rem] tracking-[-.06em]",
  demoFlag: "m-0 text-xs tracking-[.02em] text-[var(--muted)]",
  wardBand: "mx-auto flex w-full max-w-[var(--content-max,76rem)] items-center justify-between gap-4 border-b border-[var(--rule)] px-[clamp(1.25rem,4vw,2rem)] py-4 max-[41.99rem]:items-start",
  wardIdentity: "min-w-0 [&_h1]:m-0 [&_h1]:text-[clamp(1.25rem,2.5vw,1.55rem)] [&_h1]:leading-tight [&_h1]:tracking-[-.035em] [&_h1_span]:font-semibold [&_h1_span]:text-[var(--muted)]",
  wardLocation: "mb-0 mt-1 inline-flex items-center gap-1.5 text-[.88rem] leading-snug text-[var(--muted)] [&_svg]:shrink-0",
  kicker: "mb-[.35rem] mt-0 text-[.78rem] font-semibold uppercase leading-[1.35] tracking-[.065em] text-[var(--muted)]",
  wardSwitcher: "inline-flex min-h-11 shrink-0 items-center justify-center gap-[.25rem] whitespace-nowrap border-0 bg-transparent py-2 pl-3 pr-0 text-[.9rem] font-semibold text-[var(--indigo)]",
  nav: "sticky top-0 z-[4] mx-auto flex w-full max-w-[var(--content-max,76rem)] overscroll-contain overflow-x-auto border-b border-[var(--rule)] bg-[color-mix(in_oklch,var(--paper)_94%,transparent)] px-[clamp(1.25rem,4vw,2rem)] backdrop-blur-sm [scrollbar-width:none] [&_button]:relative [&_button]:min-h-11 [&_button]:shrink-0 [&_button]:border-0 [&_button]:bg-transparent [&_button]:px-[clamp(.7rem,2vw,1rem)] [&_button]:py-2 [&_button]:font-semibold [&_button]:text-[var(--muted)] [&_button]:transition-colors [&_button]:hover:text-[var(--indigo)] [&_button]:after:absolute [&_button]:after:bottom-0 [&_button]:after:left-3 [&_button]:after:right-3 [&_button]:after:h-0.5 [&_button]:after:origin-center [&_button]:after:scale-x-0 [&_button]:after:bg-[var(--indigo)] [&_button]:after:transition-transform",
  navActive: "!text-[var(--indigo)] after:!scale-x-100",
  main: "mx-auto w-full max-w-[var(--content-max,76rem)] flex-1 px-[clamp(1.25rem,4vw,2rem)] pb-16 pt-[clamp(1.5rem,3vw,2.5rem)] [&_h2]:m-0 [&_h2]:max-w-[15ch] [&_h2]:tracking-[-.05em] [&_h2]:leading-[1.05]",
  homeLead: "grid items-center gap-5 min-[42rem]:grid-cols-[minmax(0,1fr)_auto] [&_h2]:max-w-[18ch] [&_h2]:text-[clamp(1.75rem,3.4vw,2.5rem)]",
  latestNotice: "mb-8 grid gap-3 border-l-4 border-[var(--marigold)] bg-[color-mix(in_oklch,var(--marigold)_14%,var(--paper))] px-5 py-4 min-[42rem]:grid-cols-[minmax(0,1fr)_auto] min-[42rem]:items-end min-[42rem]:gap-6 [&_.kicker]:mb-1 [&_h2]:max-w-[48ch] [&_h2]:text-[clamp(1.1rem,2vw,1.45rem)] [&_h2]:leading-[1.35] [&_h2]:tracking-[-.025em]",
  municipalityNotice: "mb-8 grid gap-3 border-l-4 border-[var(--indigo)] bg-[color-mix(in_oklch,var(--indigo-soft)_65%,var(--paper))] px-5 py-4 min-[42rem]:grid-cols-[minmax(0,1fr)_auto] min-[42rem]:items-end min-[42rem]:gap-6 [&_.kicker]:mb-1 [&_.kicker]:text-[var(--indigo)] [&_h2]:max-w-[48ch] [&_h2]:text-[clamp(1.1rem,2vw,1.45rem)] [&_h2]:leading-[1.35] [&_h2]:tracking-[-.025em]",
  latestNoticeMeta: "m-0 text-[.8rem] leading-[1.45] text-[var(--muted)] min-[42rem]:text-right",
  latestNoticeBody: "m-0 mt-2 max-w-[64ch] text-[.98rem] leading-[1.5] text-[var(--muted)]",
  leadCopy: "mb-0 mt-2 max-w-[58ch] text-[1rem] leading-[1.5] text-[var(--muted)]",
  primaryAction: "inline-flex min-h-12 cursor-pointer items-center justify-center gap-2 rounded border border-[var(--indigo)] bg-[var(--indigo)] px-4 py-[.7rem] font-semibold !text-[oklch(99%_.003_240)] disabled:cursor-wait disabled:opacity-[.78] hover:bg-[oklch(34%_.13_252)]",
  secondaryAction: "inline-flex min-h-12 cursor-pointer items-center justify-center gap-2 rounded border border-[var(--indigo)] bg-transparent px-4 py-[.7rem] font-semibold text-[var(--indigo)] hover:bg-[var(--indigo-soft)]",
  submitSpinner: "h-4 w-4 shrink-0 animate-spin rounded-full border-[.15rem] border-current/30 border-t-current",
  pulse: "mt-6 grid grid-cols-2 border-y border-[var(--rule)] [&_button]:min-h-[76px] [&_button]:border-0 [&_button]:border-r [&_button]:border-[var(--rule)] [&_button]:bg-transparent [&_button]:p-[.85rem_.5rem] [&_button]:text-left [&_button]:last:border-r-0 [&_button]:hover:bg-[color-mix(in_oklch,var(--indigo-soft)_50%,transparent)] [&_strong]:block [&_strong]:text-[clamp(1.5rem,4vw,2rem)] [&_strong]:leading-none [&_strong]:tabular-nums [&_span]:mt-1.5 [&_span]:block [&_span]:text-[.78rem] [&_span]:font-semibold [&_span]:text-[var(--muted)] min-[42rem]:grid-cols-4 min-[42rem]:[&_button]:px-4",
  homeGrid: "mt-8 grid gap-9 min-[60rem]:grid-cols-[minmax(0,1.6fr)_minmax(17rem,.8fr)] min-[60rem]:gap-14",
  section: "",
  sectionHead: "mb-5 flex items-end justify-between gap-4",
  homeEmpty: "border-y border-[var(--rule)] bg-[color-mix(in_oklch,var(--indigo-soft)_45%,transparent)] px-5 py-6 [&_h3]:m-0 [&_h3]:text-[clamp(1.15rem,2.6vw,1.35rem)] [&_h3]:leading-[1.2] [&_h3]:tracking-[-.03em]",
  homeEmptyCopy: "mb-0 mt-2 max-w-[42ch] leading-[1.55] text-[var(--muted)]",
  homeEmptyActions: "mt-5 flex flex-wrap items-center gap-3",
  textAction: "inline-flex min-h-11 items-center justify-center gap-[.35rem] whitespace-nowrap border-0 bg-transparent px-0 py-2 text-[.9rem] font-bold text-[var(--indigo)]",
  issueRecord: "min-w-0 overflow-hidden border-t border-[var(--rule)] py-5 motion-safe:animate-[rise_.45s_cubic-bezier(.16,1,.3,1)_both]",
  issueOpen: "block min-w-0 w-full cursor-pointer border-0 bg-transparent p-0 text-left [&_h3]:mb-[.35rem] [&_h3]:mt-[.7rem] [&_h3]:text-[clamp(1.05rem,2vw,1.25rem)] [&_h3]:leading-[1.3] [&_h3]:tracking-[-.025em] [&_p]:m-0 [&_p]:leading-[1.5] [&_p]:text-[var(--muted)] hover:[&_h3]:text-[var(--indigo)]",
  issueEyebrow: "flex min-w-0 items-center justify-between gap-3 text-[.76rem] font-semibold tracking-[.055em] text-[var(--muted)] [&>span:first-child]:min-w-0 [&>span:first-child]:truncate [&>span:last-child]:shrink-0",
  issueMeta: "mt-3 flex min-w-0 flex-wrap gap-x-3 gap-y-[.4rem] text-[.78rem] text-[var(--muted)]",
  rejectionSummary: "mt-4 border-l-2 border-[var(--red)] bg-[oklch(96%_.025_27)] px-3 py-2 text-[.82rem] leading-[1.45] text-[var(--ink)] [&_strong]:text-[var(--red)] [&_small]:mt-1 [&_small]:block [&_small]:text-[var(--muted)]",
  escalated: "font-bold text-[var(--red)]",
  escalationStatus: "font-bold text-[var(--red)]",
  escalationStatusDot: "!bg-[var(--red)]",
  escalationNotice: "my-5 grid gap-1 border-l-[3px] border-[var(--red)] bg-[oklch(96%_.025_27)] px-4 py-3 text-[.86rem] leading-[1.4] [&_strong]:text-[var(--red)] [&_span]:text-[var(--muted)]",
  status: "inline-flex items-center gap-[.33rem] whitespace-nowrap text-[.72rem] font-bold text-[var(--ink)]",
  statusDot: "h-2 w-2 rounded-full bg-[var(--marigold)]",
  status_requested: "",
  status_in_progress: "[&_span:first-child]:bg-[var(--indigo)]",
  status_completed: "[&_span:first-child]:bg-[var(--green)]",
  status_rejected: "[&_span:first-child]:bg-[var(--red)]",
  hindiHint: "font-semibold text-[var(--muted)]",
  voteRow: "mt-4 flex w-full min-w-0 flex-wrap items-center gap-[.4rem] [&>button]:shrink-0",
  voteSummary: "mt-4 flex flex-wrap items-center gap-x-3 gap-y-1 text-[.78rem] font-semibold text-[var(--muted)]",
  voteNotice: "py-2 text-[.8rem] font-semibold text-[var(--muted)]",
  voteButton: "inline-flex min-h-11 min-w-0 cursor-pointer items-center justify-center gap-[.45rem] border border-[var(--rule)] bg-transparent px-[.7rem] py-[.55rem] hover:bg-[var(--indigo-soft)] [&_strong]:tabular-nums",
  votedUp: "border-[var(--green)] bg-[var(--green-soft)] text-[oklch(30%_.07_175)]",
  votedDown: "border-[var(--red)] text-[var(--red)]",
  sideLedger: "border-t-[3px] border-[var(--marigold)]",
  miniSection: "border-b border-[var(--rule)] py-5 [&_h2]:text-[clamp(1.15rem,2.4vw,1.4rem)] [&>p:not(.kicker)]:mt-2 [&>p:not(.kicker)]:leading-[1.55] [&>p:not(.kicker)]:text-[var(--muted)]",
  profileButton: "mb-2 inline-flex max-w-full cursor-pointer flex-wrap items-center gap-x-4 gap-y-2 border-0 bg-transparent p-0 text-left [&_h2]:leading-tight [&_span]:inline-flex [&_span]:items-center [&_span]:gap-[.2rem] [&_span]:whitespace-nowrap [&_span]:text-[.78rem] [&_span]:font-bold [&_span]:text-[var(--indigo)]",
  profilePage: "max-w-[56rem] [&>h2]:my-[.55rem_.35rem] [&>h2]:max-w-none [&>h2]:text-[clamp(2rem,4.5vw,3.75rem)]",
  profileEmpty: "mt-12 max-w-[42rem] border-t-[3px] border-[var(--marigold)] pt-6 [&_h2]:my-[.55rem_.35rem] [&_h2]:max-w-[14ch] [&_h2]:text-[clamp(1.9rem,4.5vw,3rem)] [&_p:last-child]:max-w-[55ch] [&_p:last-child]:leading-[1.6] [&_p:last-child]:text-[var(--muted)]",
  profileEmptyIcon: "mb-5 inline-flex h-12 w-12 items-center justify-center bg-[var(--indigo-soft)] text-[var(--indigo)]",
  profileRole: "m-0 text-[clamp(1rem,1.5vw,1.15rem)] text-[var(--muted)]",
  profileGrid: "my-10 grid gap-5 [&_section]:border-t-[3px] [&_section]:border-[var(--marigold)] [&_section]:py-5 [&_section_h3]:mb-2 [&_section_h3]:mt-0 [&_section_h3]:text-[clamp(1.4rem,3vw,1.75rem)] [&_section_h3]:leading-[1.15] [&_section_p:last-child]:m-0 [&_section_p:last-child]:leading-[1.6] [&_section_p:last-child]:text-[var(--muted)]",
  profileMetric: "!font-serif !text-[clamp(2rem,5vw,3.2rem)] !leading-none !tracking-[-.05em] !tabular-nums",
  finePrint: "mt-3 block text-[.8rem] text-[var(--muted)]",
  publicWork: "mt-15 border-t-[3px] border-[var(--ink)] pt-5 motion-safe:animate-[rise_.45s_cubic-bezier(.16,1,.3,1)_both]",
  budgetNumber: "m-0 text-right text-[1.2rem] font-bold tabular-nums text-[var(--indigo)] [&_span]:mt-[.2rem] [&_span]:block [&_span]:text-[.75rem] [&_span]:font-semibold [&_span]:text-[var(--muted)]",
  budgetTrack: "my-6 h-[.65rem] overflow-hidden bg-[var(--indigo-soft)] [&_span]:block [&_span]:h-full [&_span]:bg-[var(--green)]",
  workGrid: "grid gap-8 min-[42rem]:grid-cols-2 min-[42rem]:gap-12 [&_h3]:mb-3 [&_h3]:mt-0 [&_h3]:text-[.92rem] [&_h3]:uppercase [&_h3]:tracking-[.05em] [&_p]:m-0 [&_p]:flex [&_p]:justify-between [&_p]:gap-3 [&_p]:border-t [&_p]:border-[var(--rule)] [&_p]:py-[.7rem] [&_p]:leading-[1.45] [&_p]:text-[var(--muted)] [&_p_strong]:shrink-0 [&_p_strong]:text-[.86rem] [&_p_strong]:text-[var(--ink)] [&_p_strong]:tabular-nums",
  doneTask: "font-bold text-[var(--green)]",
  issueBoard: "[container-type:inline-size]",
  filterBar: "my-6 flex gap-2 overflow-x-auto pb-1 [&_button]:min-h-11 [&_button]:shrink-0 [&_button]:rounded-full [&_button]:border [&_button]:border-[var(--rule)] [&_button]:bg-transparent [&_button]:px-[.8rem] [&_button]:py-2 [&_button]:text-[.88rem] [&_button]:font-bold",
  filterActive: "!border-[var(--indigo)] !bg-[var(--indigo)] !text-[oklch(99%_.003_240)]",
  historyIntro: "mb-6 border-l-[3px] border-[var(--red)] bg-[oklch(96%_.025_27)] px-4 py-3 [&_.kicker]:mb-1 [&>p:last-child]:m-0 [&>p:last-child]:leading-[1.5] [&>p:last-child]:text-[var(--muted)]",
  boardLayout: "grid items-start gap-8 min-[60rem]:grid-cols-[minmax(0,1.25fr)_minmax(20rem,.75fr)] min-[60rem]:gap-12",
  issueList: "min-w-0",
  detailPanel: "min-h-[19rem] border border-[var(--rule)] bg-[oklch(99%_.004_240)] min-[60rem]:sticky min-[60rem]:top-4",
  detailEmpty: "grid min-h-[19rem] place-items-center p-8 text-center text-[var(--muted)] [&_h3]:mt-3 [&_h3]:text-[var(--ink)] [&_p]:max-w-[25ch] [&_p]:leading-[1.5]",
  detailContent: "p-5 [&_h3]:mb-3 [&_h3]:mt-3 [&_h3]:text-[clamp(1.3rem,3vw,1.65rem)] [&_h3]:leading-[1.18] [&_h3]:tracking-[-.035em]",
  detailTop: "mb-4 flex items-center justify-end [&_button]:h-11 [&_button]:w-11 [&_button]:border-0 [&_button]:bg-transparent",
  detailDescription: "m-0 leading-[1.6] text-[var(--muted)]",
  statusTrail: "my-6 border-t-[3px] border-[var(--marigold)] pt-4",
  statusTrailHeader: "mb-4 flex items-center justify-between gap-3 [&_.kicker]:mb-0 [&>span]:text-[.75rem] [&>span]:font-semibold [&>span]:text-[var(--muted)]",
  statusTrailList: "m-0 list-none p-0",
  statusTrailItem: "grid grid-cols-[1rem_minmax(0,1fr)] gap-3 pb-5 last:pb-0",
  statusTrailRail: "relative flex justify-center border-l border-[var(--rule)]",
  statusTrailMarker: "relative z-[1] mt-[.3rem] h-[.65rem] w-[.65rem] shrink-0 rounded-full bg-[var(--indigo)] ring-4 ring-[var(--paper)]",
  statusTrailMarker_requested: "bg-[var(--marigold)]",
  statusTrailMarker_in_progress: "bg-[var(--indigo)]",
  statusTrailMarker_completed: "bg-[var(--green)]",
  statusTrailMarker_rejected: "bg-[var(--red)]",
  statusTrailMeta: "flex flex-wrap items-baseline justify-between gap-x-3 gap-y-1 text-[.8rem] [&_strong]:font-bold [&_time]:text-[var(--muted)]",
  statusTrailBody: "min-w-0 [&>p]:m-0 [&>p]:mt-1.5 [&>p]:leading-[1.5] [&>p]:text-[.84rem] [&>p]:text-[var(--muted)] [&>small]:mt-1 [&>small]:block [&>small]:text-[.75rem] [&>small]:font-semibold [&>small]:text-[var(--muted)]",
  rejectionNotice: "my-5 border-l-[3px] border-[var(--red)] bg-[color-mix(in_oklch,var(--red)_8%,var(--paper))] px-4 py-3 [&_.kicker]:mb-1 [&>p:not(.kicker)]:m-0 [&>p:not(.kicker)]:leading-[1.5]",
  rejectionFacts: "mt-3 grid gap-2 border-t border-[color-mix(in_oklch,var(--red)_22%,var(--rule))] pt-3 text-[.82rem] [&_div]:flex [&_div]:justify-between [&_div]:gap-3 [&_dt]:text-[var(--muted)] [&_dd]:m-0 [&_dd]:text-right [&_dd]:font-semibold",
  recordFacts: "my-6 [&_div]:grid [&_div]:grid-cols-2 [&_div]:gap-4 [&_div]:border-t [&_div]:border-[var(--rule)] [&_div]:py-[.65rem] [&_dt]:text-[.82rem] [&_dt]:text-[var(--muted)] [&_dd]:m-0 [&_dd]:text-right [&_dd]:text-[.87rem] [&_dd]:font-bold",
  evidence: "border-t-[3px] border-[var(--marigold)] pt-4 [&_h4]:mb-3 [&_h4]:mt-0 [&_h4]:text-[.85rem] [&_h4]:uppercase [&_h4]:tracking-[.06em] [&>p]:text-[.9rem] [&>p]:leading-[1.5] [&>p]:text-[var(--muted)]",
  evidenceList: "grid gap-[.6rem]",
  evidenceItem: "grid grid-cols-[5.5rem_minmax(0,1fr)] items-center gap-3 bg-[var(--indigo-soft)] p-[.65rem]",
  evidencePreview: "relative h-[4.5rem] w-[5.5rem] cursor-pointer overflow-hidden border border-[var(--rule)] bg-[oklch(91%_.025_244)] p-0 transition hover:border-[var(--indigo)] disabled:cursor-wait disabled:opacity-75 focus-visible:outline-3 focus-visible:outline-[var(--marigold)] [&_img]:h-full [&_img]:w-full [&_img]:object-cover [&_img]:transition [&_img]:duration-200 [&_video]:h-full [&_video]:w-full [&_video]:object-cover hover:[&_img]:scale-105",
  mediaUnavailable: "grid h-full w-full place-items-center text-[var(--muted)]",
  playBadge: "absolute inset-0 grid place-items-center bg-[oklch(18%_.025_267/.4)] text-[var(--paper)]",
  audioPreview: "grid h-full w-full place-items-center bg-[var(--paper)] text-[var(--indigo)]",
  evidenceMeta: "min-w-0 [&>span]:flex [&>span]:items-center [&>span]:gap-[.4rem] [&>span]:text-[.88rem] [&>span]:font-bold [&>small]:mt-1 [&>small]:block [&>small]:truncate [&>small]:text-[var(--muted)]",
  evidenceIcon: "inline-flex shrink-0 items-center justify-center",
  mediaLightbox: "fixed inset-0 z-50 grid place-items-center bg-[oklch(18%_.025_267/.78)] p-4 backdrop-blur-[2px]",
  mediaLightboxPanel: "relative flex max-h-[min(90vh,52rem)] w-full max-w-[68rem] flex-col gap-4 overflow-hidden border border-[var(--rule)] bg-[var(--paper)] p-4 shadow-[0_24px_70px_oklch(10%_.03_267/.4)]",
  mediaLightboxTop: "flex items-start justify-between gap-4 [&_.kicker]:mb-1 [&_h3]:m-0 [&_h3]:max-w-[38ch] [&_h3]:overflow-hidden [&_h3]:text-ellipsis [&_h3]:text-[1rem] [&_h3]:font-bold",
  mediaLightboxClose: "inline-flex h-11 w-11 shrink-0 cursor-pointer items-center justify-center border-0 bg-transparent text-[var(--ink)] hover:bg-[var(--indigo-soft)] focus-visible:outline-3 focus-visible:outline-[var(--marigold)]",
  mediaLightboxMedia: "max-h-[calc(90vh-8rem)] w-full object-contain bg-[oklch(18%_.025_267)]",
  mediaLightboxAudio: "w-full",
  privacyNote: "mt-5 text-[.8rem] leading-[1.5] text-[var(--muted)]",
  emptyState: "my-8 leading-[1.5] text-[var(--muted)]",
  reportFlow: "max-w-[46rem] [&_h2]:max-w-none",
  backButton: "mb-8 inline-flex min-h-11 items-center justify-center gap-[.35rem] border-0 bg-transparent p-0 font-bold text-[var(--indigo)]",
  reportForm: "grid gap-5",
  formField: "grid gap-2 [&_label]:font-bold [&_input]:w-full [&_input]:rounded-[.2rem] [&_input]:border [&_input]:border-[oklch(62%_.025_245)] [&_input]:bg-[oklch(99%_.004_240)] [&_input]:p-[.85rem] [&_input]:text-[1rem] [&_input]:leading-[1.5] [&_textarea]:w-full [&_textarea]:resize-y [&_textarea]:rounded-[.2rem] [&_textarea]:border [&_textarea]:border-[oklch(62%_.025_245)] [&_textarea]:bg-[oklch(99%_.004_240)] [&_textarea]:p-[.85rem] [&_textarea]:text-[1rem] [&_textarea]:leading-[1.5] [&_p]:m-0 [&_p]:text-[.84rem] [&_p]:leading-[1.5] [&_p]:text-[var(--muted)]",
  attachments: "m-0 border-0 border-t border-[var(--rule)] pb-0 pt-4 [&_legend]:font-bold [&_legend_span]:font-normal [&_legend_span]:text-[var(--muted)] [&>input]:w-full [&>input]:border [&>input]:border-dashed [&>input]:border-[oklch(62%_.025_245)] [&>input]:bg-[oklch(99%_.004_240)] [&>input]:p-[.7rem] [&>input]:text-[var(--ink)] [&>p]:m-0 [&>p]:text-[.84rem] [&>p]:leading-[1.5] [&>p]:text-[var(--muted)]",
  formError: "m-0 border-l-[3px] border-[var(--red)] bg-[oklch(96%_.025_27)] p-3 leading-[1.45] text-[oklch(33%_.1_27)]",
  duplicateNotice: "border-l-[3px] border-[var(--marigold)] bg-[color-mix(in_oklch,var(--marigold)_12%,var(--paper))] p-4 [&_.kicker]:mb-1 [&>p:not(.kicker)]:m-0 [&>p:not(.kicker)]:leading-[1.5] [&_ul]:my-3 [&_ul]:pl-5 [&_li]:leading-[1.45] [&_small]:ml-1 [&_small]:text-[.78rem] [&_small]:text-[var(--muted)] [&_button]:mt-1",
  successState: "max-w-[38rem] py-[clamp(1.5rem,5vw,3rem)] [&_h3]:mb-[.65rem] [&_h3]:mt-4 [&_h3]:text-[1.65rem] [&_h3]:tracking-[-.035em] [&_p]:mb-6 [&_p]:mt-0 [&_p]:leading-[1.6] [&_p]:text-[var(--muted)]",
  successMark: "grid h-14 w-14 place-items-center rounded-full bg-[var(--green-soft)] text-[var(--green)]",
  wardBrowser: "[&_h2]:max-w-none",
  yourWardCard: "mt-7 flex items-center justify-between gap-5 border-l-4 border-[var(--green)] bg-[var(--green-soft)] p-[1.1rem_1.2rem] max-[41.99rem]:items-start max-[41.99rem]:flex-col [&_.kicker]:mb-1 [&_.kicker]:text-[var(--green)] [&_strong]:block [&_strong]:text-[1.15rem] [&_p:last-child]:mb-0 [&_p:last-child]:mt-1 [&_p:last-child]:text-[.86rem] [&_p:last-child]:text-[var(--ink)]",
  wardList: "mt-8 grid gap-0 border-t border-[var(--rule)] min-[42rem]:grid-cols-2 min-[42rem]:gap-x-10 min-[60rem]:grid-cols-3 [&_button]:grid [&_button]:min-h-[68px] [&_button]:w-full [&_button]:grid-cols-[4.8rem_1fr_auto] [&_button]:items-center [&_button]:gap-2 [&_button]:border-0 [&_button]:border-b [&_button]:border-[var(--rule)] [&_button]:bg-transparent [&_button]:py-3 [&_button]:text-left [&_button]:hover:text-[var(--indigo)] [&_button>span]:text-[.82rem] [&_button>span]:font-bold [&_button>span]:text-[var(--muted)] [&_button>small]:col-start-2 [&_button>small]:text-[var(--muted)] [&_button>svg]:col-start-3 [&_button>svg]:row-span-2 [&_button>svg]:text-[var(--indigo)]",
  wardSelected: "!bg-[var(--indigo-soft)] !px-3 !text-[var(--indigo)]",
  wardResident: "[&>span]:font-bold",
  footer: "mx-auto mt-auto w-full max-w-[var(--content-max,76rem)] border-t border-[var(--rule)] px-[clamp(1.25rem,4vw,2rem)] py-5 text-[.78rem] leading-[1.45] text-[var(--muted)]",
  srOnly: "sr-only",
};

export default styles;
